# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Call tagger inside 'tbb::parallel_for' and return a list of named character vectors.
#'
#' @param text Character vector.
#' @param sys_dic String scalar.
#' @param user_dic String scalar.
#' @return list of named character vectors.
#'
#' @name posParallelRcpp
#' @keywords internal
#' @export
NULL

#' Call tagger inside 'tbb::parallel_for' and return a named list.
#'
#' @param text Character vector.
#' @param sys_dic String scalar.
#' @param user_dic String scalar.
#' @return named list.
#'
#' @name posParallelJoinRcpp
#' @keywords internal
#' @export
NULL

#' Call tagger inside 'tbb::parallel_for' and return a data.frame
#'
#' @param text Character vector.
#' @param sys_dic String scalar.
#' @param user_dic String scalar.
#' @return data.frame.
#'
#' @name posParallelDFRcpp
#' @keywords internal
#' @export
NULL

posParallelRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posParallelRcpp`, text, sys_dic, user_dic)
}

posParallelJoinRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posParallelJoinRcpp`, text, sys_dic, user_dic)
}

posParallelDFRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posParallelDFRcpp`, text, sys_dic, user_dic)
}

#' Call tagger inside a loop and return a list of named character vectors.
#'
#' @param text Character vector.
#' @param sys_dic String scalar.
#' @param user_dic String scalar.
#' @return list of named character vectors.
#'
#' @name posLoopRcpp
#' @keywords internal
#' @export
NULL

#' Call tagger inside a loop and return a named list.
#'
#' @param text Character vector.
#' @param sys_dic String scalar.
#' @param user_dic String scalar.
#' @return named list.
#'
#' @name posLoopJoinRcpp
#' @keywords internal
#' @export
NULL

#' Call tagger inside a loop and return a data.frame
#'
#' @param text Character vector.
#' @param sys_dic String scalar.
#' @param user_dic String scalar.
#' @return data.frame.
#'
#' @name posLoopDFRcpp
#' @keywords internal
#' @export
NULL

posLoopRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posLoopRcpp`, text, sys_dic, user_dic)
}

posLoopJoinRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posLoopJoinRcpp`, text, sys_dic, user_dic)
}

posLoopDFRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posLoopDFRcpp`, text, sys_dic, user_dic)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_RcppMeCab_RcppExport_registerCCallable', PACKAGE = 'RcppMeCab')
})
