# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

posParallelJoinRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posParallelJoinRcpp`, text, sys_dic, user_dic)
}

posParallelDFRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posParallelDFRcpp`, text, sys_dic, user_dic)
}

posParallelRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posParallelRcpp`, text, sys_dic, user_dic)
}

posApplyRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posApplyRcpp`, text, sys_dic, user_dic)
}

posApplyJoinRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posApplyJoinRcpp`, text, sys_dic, user_dic)
}

posApplyDFRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posApplyDFRcpp`, text, sys_dic, user_dic)
}

posLoopDFRcpp <- function(text, sys_dic, user_dic) {
    .Call(`_RcppMeCab_posLoopDFRcpp`, text, sys_dic, user_dic)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_RcppMeCab_RcppExport_registerCCallable', PACKAGE = 'RcppMeCab')
})
