name: R-CMD-check

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  check:
    strategy:
      matrix:
        mecab_lang: ['ja', 'ko']
        platform: [ubuntu-latest, macos-latest, windows-latest]
        r-version: ['release']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install libcurl-dev
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install MeCab for Japanese (Ubuntu)
        if: ${{ matrix.platform == 'ubuntu-latest' && matrix.mecab_lang == 'ja' }}
        run: |
          sudo apt install mecab
          sudo apt install libmecab-dev
          sudo apt install mecab-ipadic-utf8
          sudo ldconfig
      - name: Install MeCab for Japanese (MacOS)
        if: ${{ matrix.platform == 'macos-latest' && matrix.mecab_lang == 'ja' }}
        run: |
          brew install mecab
          brew install mecab-ipadic
      - name: Install MeCab for Korean (Ubuntu)
        if: ${{ matrix.platform == 'ubuntu-latest' && matrix.mecab_lang == 'ko' }}
        run: |
          mkdir mecab
          cd mecab
          wget "https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz" -O mecab-0.996-ko-0.9.2.tar.gz
          tar zxfv mecab-0.996-ko-0.9.2.tar.gz mecab-0.996-ko-0.9.2/
          cd mecab-0.996-ko-0.9.2/
          ./configure
          make
          make check
          sudo make install
          sudo ldconfig
          cd ../
          wget "https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/mecab-ko-dic-2.1.1-20180720.tar.gz" -O mecab-ko-dic-2.1.1-20180720.tar.gz
          tar zxfv mecab-ko-dic-2.1.1-20180720.tar.gz mecab-ko-dic-2.1.1-20180720/
          cd mecab-ko-dic-2.1.1-20180720/
          ./autogen.sh
          ./configure
          make
          sudo make install
          cd ../../
      - name: Install MeCab for Korean (MacOS)
        if: ${{ matrix.platform == 'macos-latest' && matrix.mecab_lang == 'ko' }}
        run: |
          brew install mecab-ko
          brew install mecab-ko-dic
      - name: Install dependencies
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages(c("remotes", "rcmdcheck", "covr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        env:
          MECAB_LANG: ${{ matrix.mecab_lang }}
        run: rcmdcheck::rcmdcheck(args = c("--no-multiarch", "--no-manual", "--as-cran"), build_args = c("--no-manual", "--no-build-vignettes"), error_on = "error")
        shell: Rscript {0}
      - name: Codecov
        run: covr::codecov()
        shell: Rscript {0}
