name: R-CMD-check

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  check:
    strategy:
      matrix:
        mecab_lang: ['ja', 'ko']
        platform: [ubuntu-latest]
        r-version: ['release']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install Japanese MeCab for Ubuntu
        if: ${{ matrix.platform == 'ubuntu-latest' && matrix.mecab_lang == 'ja' }}
        run: |
          sudo apt install libcurl4-openssl-dev
          sudo apt install mecab libmecab-dev mecab-ipadic-utf8
          sudo ldconfig
      - name: Install Korean MeCab for Ubuntu
        if: ${{ matrix.platform == 'ubuntu-latest' && matrix.mecab_lang == 'ko' }}
        run: |
          sudo apt install libcurl4-openssl-dev
          mkdir mecab
          cd mecab
          wget "https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz" -O mecab-0.996-ko-0.9.2.tar.gz
          tar zxfv mecab-0.996-ko-0.9.2.tar.gz mecab-0.996-ko-0.9.2/
          cd mecab-0.996-ko-0.9.2/
          ./configure
          make
          make check
          sudo make install
          sudo ldconfig
          echo `mecab-config --libexecdir` >> $GITHUB_PATH
          cd ../
          wget "https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/mecab-ko-dic-2.1.1-20180720.tar.gz" -O mecab-ko-dic-2.1.1-20180720.tar.gz
          tar zxfv mecab-ko-dic-2.1.1-20180720.tar.gz mecab-ko-dic-2.1.1-20180720/
          cd mecab-ko-dic-2.1.1-20180720/
          ./autogen.sh
          ./configure
          make
          sudo make install
          cd ../../
      - name: Install deps
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check package
        uses: r-lib/actions/check-r-package@v2
        env:
          MECAB_LANG: ${{ matrix.mecab_lang }}
        with:
          args: 'c("--no-vignettes", "--no-manual", "--ignore-vignettes")'
          build_args: 'c("--no-build-vignettes", "--no-manual")'
          error-on: '"error"'
